name: idm
channels:
  - conda-forge
dependencies:
  - python==3.8.13
  - pip
  - matplotlib
  - numpy
  - pandas
  - requests
  - scikit-learn
  - opencv
  - pip: 
       - cvzone
       - mediapipe
       - protobuf~=3.19.0
# prefix: /home/
