name: idm
channels:
  - conda-forge
dependencies:
  - python
  - flask
  - jupyter
  - pip
  - matplotlib
  - numpy
  - pandas
  - requests
  - scikit-learn
  - opencv
  - keras
  - tensorflow
  - requests
  # - endpoints
  # - pip: 
  #      - cvzone
  #      - mediapipe
  #      - protobuf~=3.19.0
# prefix: /home/
